//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Varigence Ast Designer tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.  Do not edit this file unless you know exactly
//     you are doing and are synchronized with the Vulcan development team.
//
//     For more information about the Varigence Ast Designer tool, email
//     support@varigence.com.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Specialized;
using Vulcan.Utility.ComponentModel;
using AstFramework;
using AstFramework.Engine.Binding;
using AstFramework.Model;
using AstFramework.Markup;
using VulcanEngine.AstFramework;
using Vulcan.Utility.Collections;
using System.Reflection;
using System.Collections.Generic;
using Vulcan.Utility.Xml;
using Vulcan.Utility.Common;
using Vulcan.Utility.Markup;

namespace VulcanEngine.IR.Ast.Table
{
    [FriendlyNameAttribute("MappedTableColumnReference")]
    [AstSchemaTypeBindingAttribute("", "http://tempuri.org/vulcan2.xsd")]
    public partial class AstMappedTableColumnReferenceNode : VulcanEngine.IR.Ast.AstNamedNode
    {
        #region Private Storage
        private VulcanEngine.IR.Ast.Table.AstTableColumnBaseNode _column;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields")]
        protected System.Boolean IsNullable_BackingField;
        private bool _isIsNullableExplicitlySet;

        #endregion Private Storage

        #region Public Accessor Properties
        [Browsable(true)]
        [AstXNameBinding("ColumnName", ChildType.Attribute)]
        public VulcanEngine.IR.Ast.Table.AstTableColumnBaseNode Column
        {
            get { return _column; }
            set
            {
                if (_column != value)
                {
                    if (_column != null)
                    {
                        _column.Unreference(this, "Column");
                    }
                    VulcanEngine.IR.Ast.Table.AstTableColumnBaseNode oldValue = _column;
                    _column = value;
                    if (_column != null)
                    {
                        _column.Reference(this, "Column");
                    }
                    VulcanOnPropertyChanged("Column", oldValue, _column);
                }
            }
        }


        [Browsable(true)]
        [AstXNameBinding("IsNullable", ChildType.Attribute)]
        public System.Boolean IsNullable
        {
            get { return IsNullable_BackingField; }
            set
            {
                if (IsNullable_BackingField != value)
                {
                    System.Boolean oldValue = IsNullable_BackingField;
                    IsNullable_BackingField = value;
                    VulcanOnPropertyChanged("IsNullable", oldValue, IsNullable_BackingField);
                    IsIsNullableExplicitlySet = true;
                }
            }
        }

        public bool IsIsNullableExplicitlySet
        {
            get { return _isIsNullableExplicitlySet; }
            protected set
            {
                if (_isIsNullableExplicitlySet != value)
                {
                    bool oldValue = _isIsNullableExplicitlySet;
                    _isIsNullableExplicitlySet = value;
                    VulcanOnPropertyChanged("IsIsNullableExplicitlySet", oldValue, _isIsNullableExplicitlySet);
                }
            }
        }


        #endregion Public Accessor Properties

        #region Collection Methods


        #endregion Collection Methods

        #region Initialization
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        private void InitializeAstNode()
        {
        }

        #endregion Initialization

        public override VulcanCollection<IFrameworkItem> DefinedAstNodes()
        {
            var definedAstNodes = new VulcanCollection<IFrameworkItem>();
            definedAstNodes.AddRange(base.DefinedAstNodes());


            return definedAstNodes;
        }


        public override IEnumerable<IScopeBoundary> BindingScopeBoundaries()
        {
            var bindingScopeBoundaries = new List<IScopeBoundary>();
            bindingScopeBoundaries.Add(ScopeBoundary);
            return bindingScopeBoundaries;
        }


        #region Cloning Support
        public override IFrameworkItem Clone()
        {
            return Clone(ParentItem);
        }

        public override IFrameworkItem Clone(Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            return Clone(ParentItem, cloneMapping);
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem)
        {
            return Clone(parentItem, new Dictionary<IFrameworkItem, IFrameworkItem>());
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            SymbolTable.GetSourceToCloneDefinitionMappings(this, parentItem, cloneMapping);
            CloneInto(cloneMapping[this], cloneMapping);
            return cloneMapping[this];
        }

        public override void CloneInto(IFrameworkItem targetItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            base.CloneInto(targetItem, cloneMapping);
            if (targetItem == null || !typeof(AstMappedTableColumnReferenceNode).IsAssignableFrom(targetItem.GetType()))
            {
                throw new ArgumentException("Provided target node is not of the correct type.");
            }
            var castedTargetItem = (AstMappedTableColumnReferenceNode)targetItem;
            if (_column == null)
            {
                castedTargetItem._column = null;
            }
            else if (cloneMapping.ContainsKey(_column))
            {
                castedTargetItem._column = (VulcanEngine.IR.Ast.Table.AstTableColumnBaseNode)cloneMapping[_column];
            }
            else
            {
                castedTargetItem._column = _column;
            }

            castedTargetItem.IsNullable_BackingField = IsNullable_BackingField;

        }

        public override IFrameworkItem CloneHusk(IFrameworkItem parentItem)
        {
            return new AstMappedTableColumnReferenceNode(parentItem);
        }

        #endregion Cloning Support


    }
}
