//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vulcan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vulcan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckAndInsert.
        /// </summary>
        internal static string CheckAndInsert {
            get {
                return ResourceManager.GetString("CheckAndInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup.
        /// </summary>
        internal static string Cleanup {
            get {
                return ResourceManager.GetString("Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataWarehouse.
        /// </summary>
        internal static string DataSourceQualifier {
            get {
                return ResourceManager.GetString("DataSourceQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string DefaultMessageEngine {
            get {
                return ResourceManager.GetString("DefaultMessageEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        internal static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dtproj.
        /// </summary>
        internal static string ExtensionDTProjectFile {
            get {
                return ResourceManager.GetString("ExtensionDTProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dtsx.
        /// </summary>
        internal static string ExtensionDTSXProjectFile {
            get {
                return ResourceManager.GetString("ExtensionDTSXProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sql.
        /// </summary>
        internal static string ExtensionSQLFile {
            get {
                return ResourceManager.GetString("ExtensionSQLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tmp.
        /// </summary>
        internal static string ExtensionTempFile {
            get {
                return ResourceManager.GetString("ExtensionTempFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLastRecordTime.
        /// </summary>
        internal static string GetLastRecordTime {
            get {
                return ResourceManager.GetString("GetLastRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init.
        /// </summary>
        internal static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAnotherInstanceCurrentlyRunningLogID.
        /// </summary>
        internal static string IsAnotherInstanceCurrentlyRunningLogID {
            get {
                return ResourceManager.GetString("IsAnotherInstanceCurrentlyRunningLogID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastSuccessfulRunLogID.
        /// </summary>
        internal static string LastSuccessfulRunLogID {
            get {
                return ResourceManager.GetString("LastSuccessfulRunLogID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load_Into_.
        /// </summary>
        internal static string LoadInto {
            get {
                return ResourceManager.GetString("LoadInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _destination.
        /// </summary>
        internal static string LogDestination {
            get {
                return ResourceManager.GetString("LogDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _source.
        /// </summary>
        internal static string LogSource {
            get {
                return ResourceManager.GetString("LogSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to varLog.
        /// </summary>
        internal static string LogVariablePrefix {
            get {
                return ResourceManager.GetString("LogVariablePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multicast Source to Log Rowset Variable.
        /// </summary>
        internal static string MulticastSourceToLog {
            get {
                return ResourceManager.GetString("MulticastSourceToLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Into.
        /// </summary>
        internal static string OLEDBDestinationNamePrefix {
            get {
                return ResourceManager.GetString("OLEDBDestinationNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre.
        /// </summary>
        internal static string Pre {
            get {
                return ResourceManager.GetString("Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordsetLogTo_.
        /// </summary>
        internal static string RecordsetLogToRowset {
            get {
                return ResourceManager.GetString("RecordsetLogToRowset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        internal static string Seperator {
            get {
                return ResourceManager.GetString("Seperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp.
        /// </summary>
        internal static string SPPrefix {
            get {
                return ResourceManager.GetString("SPPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating Template File {0}:{1}:{2}.
        /// </summary>
        internal static string TemplateManagerValidationError {
            get {
                return ResourceManager.GetString("TemplateManagerValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating VulcanConfig XML File {0}: {1}:{2}.
        /// </summary>
        internal static string VulcanConfigValidationError {
            get {
                return ResourceManager.GetString("VulcanConfigValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Vulcan Version .
        /// </summary>
        internal static string VulcanStart {
            get {
                return ResourceManager.GetString("VulcanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source {0} or Destination {1} does not exist in {2} : {3}.
        /// </summary>
        internal static string WarningMapColumnsDoNotExist {
            get {
                return ResourceManager.GetString("WarningMapColumnsDoNotExist", resourceCulture);
            }
        }
    }
}
