@echo off

SET VULCAN_PACKAGECONFIGROOT=c:\PackageConfigurations
SET VULCAN_ROOT=C:\codeplex\development-vulcan25
SET VULCANTESTROOT=%VULCAN_ROOT%\Tests
SET VULCAN_PATH_CURRENT=%PATH%;%VULCAN_ROOT%\Tools;%VULCAN_ROOT%\Tools\Vulcan\anycpu;%VULCAN_ROOT%\Tools\Vulcan\x86;

SET VULCANENGINE_PATH_CURRENT=%VULCAN_ROOT%\Tools\Vulcan\anycpu
SET VULCANENGINE86_PATH_CURRENT=%VULCAN_ROOT%\Tools\Vulcan\x86

SET PATH=%VULCAN_PATH_CURRENT%
SET VULCANENGINE_PATH=%VULCANENGINE_PATH_CURRENT%
SET VULCANENGINE86_PATH=%VULCANENGINE86_PATH_CURRENT%