//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Varigence Ast Designer tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.  Do not edit this file unless you know exactly
//     you are doing and are synchronized with the Vulcan development team.
//
//     For more information about the Varigence Ast Designer tool, email
//     support@varigence.com.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Specialized;
using Vulcan.Utility.ComponentModel;
using AstFramework;
using AstFramework.Engine.Binding;
using AstFramework.Model;
using AstFramework.Markup;
using VulcanEngine.AstFramework;
using Vulcan.Utility.Collections;
using System.Reflection;
using System.Collections.Generic;
using Vulcan.Utility.Xml;
using Vulcan.Utility.Common;
using Vulcan.Utility.Markup;

namespace VulcanEngine.IR.Ast
{
    [FriendlyNameAttribute("Permission")]
    [AstSchemaTypeBindingAttribute("PermissionElemType", "http://tempuri.org/vulcan2.xsd")]
    public partial class AstPermissionNode : VulcanEngine.IR.Ast.AstNode
    {
        #region Private Storage
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields")]
        protected VulcanEngine.IR.Ast.PermissionActionType Action_BackingField;
        private bool __isNotFirstSet_Action_BackingField;
        private bool _isActionExplicitlySet;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields")]
        protected VulcanEngine.IR.Ast.PermissionTargetType Target_BackingField;
        private bool __isNotFirstSet_Target_BackingField;
        private bool _isTargetExplicitlySet;

        private VulcanEngine.IR.Ast.Table.AstPrincipalNode _principal;
        private bool __isNotFirstSet__principal;

        #endregion Private Storage

        #region Public Accessor Properties
        [VulcanCategory("Required")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(true)]
        [AstXNameBinding("Action", ChildType.Attribute)]
        public VulcanEngine.IR.Ast.PermissionActionType Action
        {
            get { return Action_BackingField; }
            set
            {
                if (Action_BackingField != value || !__isNotFirstSet_Action_BackingField)
                {
                    __isNotFirstSet_Action_BackingField = true;
                    VulcanEngine.IR.Ast.PermissionActionType oldValue = Action_BackingField;
                    Action_BackingField = value;
                    VulcanOnPropertyChanged("Action", oldValue, Action_BackingField);
                    IsActionExplicitlySet = true;
                }
            }
        }

        public bool IsActionExplicitlySet
        {
            get { return _isActionExplicitlySet; }
            protected set
            {
                if (_isActionExplicitlySet != value)
                {
                    bool oldValue = _isActionExplicitlySet;
                    _isActionExplicitlySet = value;
                    VulcanOnPropertyChanged("IsActionExplicitlySet", oldValue, _isActionExplicitlySet);
                }
            }
        }


        [VulcanCategory("Required")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(true)]
        [AstXNameBinding("Target", ChildType.Attribute)]
        public VulcanEngine.IR.Ast.PermissionTargetType Target
        {
            get { return Target_BackingField; }
            set
            {
                if (Target_BackingField != value || !__isNotFirstSet_Target_BackingField)
                {
                    __isNotFirstSet_Target_BackingField = true;
                    VulcanEngine.IR.Ast.PermissionTargetType oldValue = Target_BackingField;
                    Target_BackingField = value;
                    VulcanOnPropertyChanged("Target", oldValue, Target_BackingField);
                    IsTargetExplicitlySet = true;
                }
            }
        }

        public bool IsTargetExplicitlySet
        {
            get { return _isTargetExplicitlySet; }
            protected set
            {
                if (_isTargetExplicitlySet != value)
                {
                    bool oldValue = _isTargetExplicitlySet;
                    _isTargetExplicitlySet = value;
                    VulcanOnPropertyChanged("IsTargetExplicitlySet", oldValue, _isTargetExplicitlySet);
                }
            }
        }


        [VulcanCategory("Required")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(true)]
        [AstXNameBinding("PrincipalName", ChildType.Attribute)]
        public VulcanEngine.IR.Ast.Table.AstPrincipalNode Principal
        {
            get { return _principal; }
            set
            {
                if (_principal != value || !__isNotFirstSet__principal)
                {
                    __isNotFirstSet__principal = true;
                    if (_principal != null)
                    {
                        _principal.Unreference(this, "Principal");
                    }
                    VulcanEngine.IR.Ast.Table.AstPrincipalNode oldValue = _principal;
                    _principal = value;
                    if (_principal != null)
                    {
                        _principal.Reference(this, "Principal");
                    }
                    VulcanOnPropertyChanged("Principal", oldValue, _principal);
                }
            }
        }


        #endregion Public Accessor Properties

        #region Collection Methods



        #endregion Collection Methods

        #region Initialization
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        private void InitializeAstNode()
        {
        }

        #endregion Initialization

        public override VulcanCollection<IFrameworkItem> DefinedAstNodes()
        {
            var definedAstNodes = new VulcanCollection<IFrameworkItem>();
            definedAstNodes.AddRange(base.DefinedAstNodes());



            return definedAstNodes;
        }


        public override IEnumerable<IScopeBoundary> BindingScopeBoundaries()
        {
            var bindingScopeBoundaries = new List<IScopeBoundary>();
            bindingScopeBoundaries.Add(ScopeBoundary);
            return bindingScopeBoundaries;
        }


        #region Cloning Support
        public override IFrameworkItem Clone()
        {
            return Clone(ParentItem);
        }

        public override IFrameworkItem Clone(Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            return Clone(ParentItem, cloneMapping);
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem)
        {
            return Clone(parentItem, new Dictionary<IFrameworkItem, IFrameworkItem>());
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            SymbolTable.GetSourceToCloneDefinitionMappings(this, parentItem, cloneMapping);
            CloneInto(cloneMapping[this], cloneMapping);
            return cloneMapping[this];
        }

        public override void CloneInto(IFrameworkItem targetItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            base.CloneInto(targetItem, cloneMapping);
            if (targetItem == null || !typeof(AstPermissionNode).IsAssignableFrom(targetItem.GetType()))
            {
                throw new ArgumentException("Provided target node is not of the correct type.");
            }
            var castedTargetItem = (AstPermissionNode)targetItem;
            castedTargetItem.Action_BackingField = Action_BackingField;

            castedTargetItem.Target_BackingField = Target_BackingField;

            if (_principal == null)
            {
                castedTargetItem._principal = null;
            }
            else if (cloneMapping.ContainsKey(_principal))
            {
                castedTargetItem._principal = (VulcanEngine.IR.Ast.Table.AstPrincipalNode)cloneMapping[_principal];
            }
            else
            {
                castedTargetItem._principal = _principal;
            }

        }

        public override IFrameworkItem CloneHusk(IFrameworkItem parentItem)
        {
            return new AstPermissionNode(parentItem);
        }

        #endregion Cloning Support


    }
}
