//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Varigence Ast Designer tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.  Do not edit this file unless you know exactly
//     you are doing and are synchronized with the Vulcan development team.
//
//     For more information about the Varigence Ast Designer tool, email
//     support@varigence.com.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Specialized;
using Vulcan.Utility.ComponentModel;
using AstFramework;
using AstFramework.Engine.Binding;
using AstFramework.Model;
using AstFramework.Markup;
using VulcanEngine.AstFramework;
using Vulcan.Utility.Collections;
using System.Reflection;
using System.Collections.Generic;
using Vulcan.Utility.Xml;
using Vulcan.Utility.Common;
using Vulcan.Utility.Markup;

namespace VulcanEngine.IR.Ast.Transformation
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1501:AvoidExcessiveInheritance")]
    [FriendlyNameAttribute("EtlFragmentReference")]
    [AstSchemaTypeBindingAttribute("EtlFragmentReferenceElemType", "http://tempuri.org/vulcan2.xsd")]
    public partial class AstEtlFragmentReferenceNode : VulcanEngine.IR.Ast.Transformation.AstSingleInTransformationNode
    {
        #region Private Storage
        private VulcanEngine.IR.Ast.Transformation.AstEtlFragmentNode _etlFragment;
        private bool __isNotFirstSet__etlFragment;

        private VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstEtlFragmentPathColumnMappingNode> _inputs;

        private VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstEtlFragmentPathColumnMappingNode> _outputs;

        #endregion Private Storage

        #region Public Accessor Properties
        [VulcanCategory("Required")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(true)]
        [AstXNameBinding("EtlFragmentName", ChildType.Attribute)]
        public VulcanEngine.IR.Ast.Transformation.AstEtlFragmentNode EtlFragment
        {
            get { return _etlFragment; }
            set
            {
                if (_etlFragment != value || !__isNotFirstSet__etlFragment)
                {
                    __isNotFirstSet__etlFragment = true;
                    if (_etlFragment != null)
                    {
                        _etlFragment.Unreference(this, "EtlFragment");
                    }
                    VulcanEngine.IR.Ast.Transformation.AstEtlFragmentNode oldValue = _etlFragment;
                    _etlFragment = value;
                    if (_etlFragment != null)
                    {
                        _etlFragment.Reference(this, "EtlFragment");
                    }
                    VulcanOnPropertyChanged("EtlFragment", oldValue, _etlFragment);
                }
            }
        }


        [VulcanCategory("Required")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(true)]
        [AstXNameBinding("Input", ChildType.ListChildDefinition)]
        public VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstEtlFragmentPathColumnMappingNode> Inputs
        {
            get { return _inputs; }
        }


        [VulcanCategory("Required")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(true)]
        [AstXNameBinding("Output", ChildType.ListChildDefinition)]
        public VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstEtlFragmentPathColumnMappingNode> Outputs
        {
            get { return _outputs; }
        }


        #endregion Public Accessor Properties

        #region Collection Methods

        private void _inputs_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            VulcanOnCollectionPropertyChanged("Inputs", e);
        }

        private void _outputs_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            VulcanOnCollectionPropertyChanged("Outputs", e);
        }

        #endregion Collection Methods

        #region Initialization
        private void InitializeAstNode()
        {
            _inputs = new VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstEtlFragmentPathColumnMappingNode>();
            _inputs.CollectionChanged += _inputs_CollectionChanged;
            _outputs = new VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstEtlFragmentPathColumnMappingNode>();
            _outputs.CollectionChanged += _outputs_CollectionChanged;
        }

        #endregion Initialization

        public override VulcanCollection<IFrameworkItem> DefinedAstNodes()
        {
            var definedAstNodes = new VulcanCollection<IFrameworkItem>();
            definedAstNodes.AddRange(base.DefinedAstNodes());

            foreach (var item in _inputs)
            {
                definedAstNodes.Add(item);
            }

            foreach (var item in _outputs)
            {
                definedAstNodes.Add(item);
            }

            return definedAstNodes;
        }


        public override IEnumerable<IScopeBoundary> BindingScopeBoundaries()
        {
            var bindingScopeBoundaries = new List<IScopeBoundary>();
            bindingScopeBoundaries.Add(ScopeBoundary);
            return bindingScopeBoundaries;
        }


        #region Cloning Support
        public override IFrameworkItem Clone()
        {
            return Clone(ParentItem);
        }

        public override IFrameworkItem Clone(Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            return Clone(ParentItem, cloneMapping);
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem)
        {
            return Clone(parentItem, new Dictionary<IFrameworkItem, IFrameworkItem>());
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            SymbolTable.GetSourceToCloneDefinitionMappings(this, parentItem, cloneMapping);
            CloneInto(cloneMapping[this], cloneMapping);
            return cloneMapping[this];
        }

        public override void CloneInto(IFrameworkItem targetItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            base.CloneInto(targetItem, cloneMapping);
            if (targetItem == null || !typeof(AstEtlFragmentReferenceNode).IsAssignableFrom(targetItem.GetType()))
            {
                throw new ArgumentException("Provided target node is not of the correct type.");
            }
            var castedTargetItem = (AstEtlFragmentReferenceNode)targetItem;
            if (_etlFragment == null)
            {
                castedTargetItem._etlFragment = null;
            }
            else if (cloneMapping.ContainsKey(_etlFragment))
            {
                castedTargetItem._etlFragment = (VulcanEngine.IR.Ast.Transformation.AstEtlFragmentNode)cloneMapping[_etlFragment];
            }
            else
            {
                castedTargetItem._etlFragment = _etlFragment;
            }

            foreach (var item in _inputs)
            {
                IFrameworkItem candidate = cloneMapping[item];
                castedTargetItem._inputs.Add((VulcanEngine.IR.Ast.Transformation.AstEtlFragmentPathColumnMappingNode)candidate);
                item.CloneInto(candidate, cloneMapping);
            }

            foreach (var item in _outputs)
            {
                IFrameworkItem candidate = cloneMapping[item];
                castedTargetItem._outputs.Add((VulcanEngine.IR.Ast.Transformation.AstEtlFragmentPathColumnMappingNode)candidate);
                item.CloneInto(candidate, cloneMapping);
            }

        }

        public override IFrameworkItem CloneHusk(IFrameworkItem parentItem)
        {
            return new AstEtlFragmentReferenceNode(parentItem);
        }

        #endregion Cloning Support


    }
}
