//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Varigence Ast Designer tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.  Do not edit this file unless you know exactly
//     you are doing and are synchronized with the Vulcan development team.
//
//     For more information about the Varigence Ast Designer tool, email
//     support@varigence.com.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Specialized;
using Vulcan.Utility.ComponentModel;
using AstFramework;
using AstFramework.Engine.Binding;
using AstFramework.Model;
using AstFramework.Markup;
using VulcanEngine.AstFramework;
using Vulcan.Utility.Collections;
using System.Reflection;
using System.Collections.Generic;
using Vulcan.Utility.Xml;
using Vulcan.Utility.Common;
using Vulcan.Utility.Markup;

namespace VulcanEngine.IR.Ast.Transformation
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1501:AvoidExcessiveInheritance")]
    [FriendlyNameAttribute("Lookup")]
    [AstSchemaTypeBindingAttribute("TransformationLookupElemType", "http://tempuri.org/vulcan2.xsd")]
    public partial class AstLookupNode : VulcanEngine.IR.Ast.Transformation.AstSingleInTransformationNode
    {
        #region Private Storage
        private VulcanEngine.IR.Ast.Connection.AstConnectionNode _connection;
        private bool __isNotFirstSet__connection;

        private VulcanEngine.IR.Ast.Task.AstQueryNode _query;
        private bool __isNotFirstSet__query;

        private VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstLookupInputOutputNode> _inputs;

        private VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstLookupInputOutputNode> _outputs;

        private VulcanEngine.IR.Ast.Transformation.AstOnDemandLookupQueryNode _onDemandLookupQuery;

        #endregion Private Storage

        #region Public Accessor Properties
        [VulcanCategory("Required")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(true)]
        [AstXNameBinding("ConnectionName", ChildType.Attribute)]
        public VulcanEngine.IR.Ast.Connection.AstConnectionNode Connection
        {
            get { return _connection; }
            set
            {
                if (_connection != value || !__isNotFirstSet__connection)
                {
                    __isNotFirstSet__connection = true;
                    if (_connection != null)
                    {
                        _connection.Unreference(this, "Connection");
                    }
                    VulcanEngine.IR.Ast.Connection.AstConnectionNode oldValue = _connection;
                    _connection = value;
                    if (_connection != null)
                    {
                        _connection.Reference(this, "Connection");
                    }
                    VulcanOnPropertyChanged("Connection", oldValue, _connection);
                }
            }
        }


        [VulcanCategory("Required")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(false)]
        [AstXNameBinding("Query", ChildType.ChildDefinition)]
        public VulcanEngine.IR.Ast.Task.AstQueryNode Query
        {
            get { return _query; }
            set
            {
                if (_query != value || !__isNotFirstSet__query)
                {
                    __isNotFirstSet__query = true;
                    VulcanEngine.IR.Ast.Task.AstQueryNode oldValue = _query;
                    _query = value;
                    VulcanOnPropertyChanged("Query", oldValue, _query);
                }
            }
        }


        [VulcanCategory("Read Only")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(false)]
        [AstXNameBinding("Input", ChildType.ListChildDefinition)]
        public VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstLookupInputOutputNode> Inputs
        {
            get { return _inputs; }
        }


        [VulcanCategory("Read Only")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(false)]
        [AstXNameBinding("Output", ChildType.ListChildDefinition)]
        public VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstLookupInputOutputNode> Outputs
        {
            get { return _outputs; }
        }


        [Browsable(false)]
        [AstXNameBinding("OnDemandLookupQuery", ChildType.ChildDefinition)]
        public VulcanEngine.IR.Ast.Transformation.AstOnDemandLookupQueryNode OnDemandLookupQuery
        {
            get { return _onDemandLookupQuery; }
            set
            {
                if (_onDemandLookupQuery != value)
                {
                    VulcanEngine.IR.Ast.Transformation.AstOnDemandLookupQueryNode oldValue = _onDemandLookupQuery;
                    _onDemandLookupQuery = value;
                    VulcanOnPropertyChanged("OnDemandLookupQuery", oldValue, _onDemandLookupQuery);
                }
            }
        }


        #endregion Public Accessor Properties

        #region Collection Methods


        private void _inputs_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            VulcanOnCollectionPropertyChanged("Inputs", e);
        }

        private void _outputs_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            VulcanOnCollectionPropertyChanged("Outputs", e);
        }


        #endregion Collection Methods

        #region Initialization
        private void InitializeAstNode()
        {
            _inputs = new VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstLookupInputOutputNode>();
            _inputs.CollectionChanged += _inputs_CollectionChanged;
            _outputs = new VulcanCollection<VulcanEngine.IR.Ast.Transformation.AstLookupInputOutputNode>();
            _outputs.CollectionChanged += _outputs_CollectionChanged;
        }

        #endregion Initialization

        public override VulcanCollection<IFrameworkItem> DefinedAstNodes()
        {
            var definedAstNodes = new VulcanCollection<IFrameworkItem>();
            definedAstNodes.AddRange(base.DefinedAstNodes());

            if (_query != null)
            {
                definedAstNodes.Add(_query);
            }

            foreach (var item in _inputs)
            {
                definedAstNodes.Add(item);
            }

            foreach (var item in _outputs)
            {
                definedAstNodes.Add(item);
            }

            if (_onDemandLookupQuery != null)
            {
                definedAstNodes.Add(_onDemandLookupQuery);
            }

            return definedAstNodes;
        }


        public override IEnumerable<IScopeBoundary> BindingScopeBoundaries()
        {
            var bindingScopeBoundaries = new List<IScopeBoundary>();
            bindingScopeBoundaries.Add(ScopeBoundary);
            return bindingScopeBoundaries;
        }


        #region Cloning Support
        public override IFrameworkItem Clone()
        {
            return Clone(ParentItem);
        }

        public override IFrameworkItem Clone(Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            return Clone(ParentItem, cloneMapping);
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem)
        {
            return Clone(parentItem, new Dictionary<IFrameworkItem, IFrameworkItem>());
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            SymbolTable.GetSourceToCloneDefinitionMappings(this, parentItem, cloneMapping);
            CloneInto(cloneMapping[this], cloneMapping);
            return cloneMapping[this];
        }

        public override void CloneInto(IFrameworkItem targetItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            base.CloneInto(targetItem, cloneMapping);
            if (targetItem == null || !typeof(AstLookupNode).IsAssignableFrom(targetItem.GetType()))
            {
                throw new ArgumentException("Provided target node is not of the correct type.");
            }
            var castedTargetItem = (AstLookupNode)targetItem;
            if (_connection == null)
            {
                castedTargetItem._connection = null;
            }
            else if (cloneMapping.ContainsKey(_connection))
            {
                castedTargetItem._connection = (VulcanEngine.IR.Ast.Connection.AstConnectionNode)cloneMapping[_connection];
            }
            else
            {
                castedTargetItem._connection = _connection;
            }

            if (_query == null)
            {
                castedTargetItem._query = null;
            }
            else if (cloneMapping.ContainsKey(_query))
            {
                castedTargetItem._query = (VulcanEngine.IR.Ast.Task.AstQueryNode)cloneMapping[_query];
                _query.CloneInto(cloneMapping[_query], cloneMapping);
            }
            else
            {
                castedTargetItem._query = _query;
            }

            foreach (var item in _inputs)
            {
                IFrameworkItem candidate = cloneMapping[item];
                castedTargetItem._inputs.Add((VulcanEngine.IR.Ast.Transformation.AstLookupInputOutputNode)candidate);
                item.CloneInto(candidate, cloneMapping);
            }

            foreach (var item in _outputs)
            {
                IFrameworkItem candidate = cloneMapping[item];
                castedTargetItem._outputs.Add((VulcanEngine.IR.Ast.Transformation.AstLookupInputOutputNode)candidate);
                item.CloneInto(candidate, cloneMapping);
            }

            if (_onDemandLookupQuery == null)
            {
                castedTargetItem._onDemandLookupQuery = null;
            }
            else if (cloneMapping.ContainsKey(_onDemandLookupQuery))
            {
                castedTargetItem._onDemandLookupQuery = (VulcanEngine.IR.Ast.Transformation.AstOnDemandLookupQueryNode)cloneMapping[_onDemandLookupQuery];
                _onDemandLookupQuery.CloneInto(cloneMapping[_onDemandLookupQuery], cloneMapping);
            }
            else
            {
                castedTargetItem._onDemandLookupQuery = _onDemandLookupQuery;
            }

        }

        public override IFrameworkItem CloneHusk(IFrameworkItem parentItem)
        {
            return new AstLookupNode(parentItem);
        }

        #endregion Cloning Support


    }
}
