//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Varigence Ast Designer tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.  Do not edit this file unless you know exactly
//     you are doing and are synchronized with the Vulcan development team.
//
//     For more information about the Varigence Ast Designer tool, email
//     support@varigence.com.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Specialized;
using Vulcan.Utility.ComponentModel;
using AstFramework;
using AstFramework.Engine.Binding;
using AstFramework.Model;
using AstFramework.Markup;
using VulcanEngine.AstFramework;
using Vulcan.Utility.Collections;
using System.Reflection;
using System.Collections.Generic;
using Vulcan.Utility.Xml;
using Vulcan.Utility.Common;
using Vulcan.Utility.Markup;

namespace VulcanEngine.IR.Ast.Transformation
{
    [FriendlyNameAttribute("Scd Type Column Mapping")]
    [AstSchemaTypeBindingAttribute("ScdTypeColumnMappingElemType", "http://tempuri.org/vulcan2.xsd")]
    public partial class AstScdTypeColumnMappingNode : VulcanEngine.IR.Ast.AstNode
    {
        #region Private Storage
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields")]
        protected System.String QueryColumnName_BackingField;
        private bool __isNotFirstSet_QueryColumnName_BackingField;
        private bool _isQueryColumnNameExplicitlySet;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields")]
        protected VulcanEngine.IR.Ast.Transformation.ScdColumnMappingType MappingType_BackingField;
        private bool __isNotFirstSet_MappingType_BackingField;
        private bool _isMappingTypeExplicitlySet;

        #endregion Private Storage

        #region Public Accessor Properties
        [VulcanCategory("Required")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(true)]
        [AstXNameBinding("QueryColumnName", ChildType.Attribute)]
        public System.String QueryColumnName
        {
            get { return QueryColumnName_BackingField; }
            set
            {
                if (QueryColumnName_BackingField != value || !__isNotFirstSet_QueryColumnName_BackingField)
                {
                    __isNotFirstSet_QueryColumnName_BackingField = true;
                    System.String oldValue = QueryColumnName_BackingField;
                    QueryColumnName_BackingField = value;
                    VulcanOnPropertyChanged("QueryColumnName", oldValue, QueryColumnName_BackingField);
                    IsQueryColumnNameExplicitlySet = true;
                }
            }
        }

        public bool IsQueryColumnNameExplicitlySet
        {
            get { return _isQueryColumnNameExplicitlySet; }
            protected set
            {
                if (_isQueryColumnNameExplicitlySet != value)
                {
                    bool oldValue = _isQueryColumnNameExplicitlySet;
                    _isQueryColumnNameExplicitlySet = value;
                    VulcanOnPropertyChanged("IsQueryColumnNameExplicitlySet", oldValue, _isQueryColumnNameExplicitlySet);
                }
            }
        }


        [VulcanCategory("Required")]
        [AstRequiredProperty]
        [VulcanDescription(@"")]
        [Browsable(true)]
        [AstXNameBinding("MappingType", ChildType.Attribute)]
        public VulcanEngine.IR.Ast.Transformation.ScdColumnMappingType MappingType
        {
            get { return MappingType_BackingField; }
            set
            {
                if (MappingType_BackingField != value || !__isNotFirstSet_MappingType_BackingField)
                {
                    __isNotFirstSet_MappingType_BackingField = true;
                    VulcanEngine.IR.Ast.Transformation.ScdColumnMappingType oldValue = MappingType_BackingField;
                    MappingType_BackingField = value;
                    VulcanOnPropertyChanged("MappingType", oldValue, MappingType_BackingField);
                    IsMappingTypeExplicitlySet = true;
                }
            }
        }

        public bool IsMappingTypeExplicitlySet
        {
            get { return _isMappingTypeExplicitlySet; }
            protected set
            {
                if (_isMappingTypeExplicitlySet != value)
                {
                    bool oldValue = _isMappingTypeExplicitlySet;
                    _isMappingTypeExplicitlySet = value;
                    VulcanOnPropertyChanged("IsMappingTypeExplicitlySet", oldValue, _isMappingTypeExplicitlySet);
                }
            }
        }


        #endregion Public Accessor Properties

        #region Collection Methods


        #endregion Collection Methods

        #region Initialization
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        private void InitializeAstNode()
        {
        }

        #endregion Initialization

        public override VulcanCollection<IFrameworkItem> DefinedAstNodes()
        {
            var definedAstNodes = new VulcanCollection<IFrameworkItem>();
            definedAstNodes.AddRange(base.DefinedAstNodes());


            return definedAstNodes;
        }


        public override IEnumerable<IScopeBoundary> BindingScopeBoundaries()
        {
            var bindingScopeBoundaries = new List<IScopeBoundary>();
            bindingScopeBoundaries.Add(ScopeBoundary);
            return bindingScopeBoundaries;
        }


        #region Cloning Support
        public override IFrameworkItem Clone()
        {
            return Clone(ParentItem);
        }

        public override IFrameworkItem Clone(Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            return Clone(ParentItem, cloneMapping);
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem)
        {
            return Clone(parentItem, new Dictionary<IFrameworkItem, IFrameworkItem>());
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            SymbolTable.GetSourceToCloneDefinitionMappings(this, parentItem, cloneMapping);
            CloneInto(cloneMapping[this], cloneMapping);
            return cloneMapping[this];
        }

        public override void CloneInto(IFrameworkItem targetItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            base.CloneInto(targetItem, cloneMapping);
            if (targetItem == null || !typeof(AstScdTypeColumnMappingNode).IsAssignableFrom(targetItem.GetType()))
            {
                throw new ArgumentException("Provided target node is not of the correct type.");
            }
            var castedTargetItem = (AstScdTypeColumnMappingNode)targetItem;
            castedTargetItem.QueryColumnName_BackingField = QueryColumnName_BackingField;

            castedTargetItem.MappingType_BackingField = MappingType_BackingField;

        }

        public override IFrameworkItem CloneHusk(IFrameworkItem parentItem)
        {
            return new AstScdTypeColumnMappingNode(parentItem);
        }

        #endregion Cloning Support


    }
}
