//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Varigence Ast Designer tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.  Do not edit this file unless you know exactly
//     you are doing and are synchronized with the Vulcan development team.
//
//     For more information about the Varigence Ast Designer tool, email
//     support@varigence.com.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Specialized;
using Vulcan.Utility.ComponentModel;
using AstFramework;
using AstFramework.Engine.Binding;
using AstFramework.Model;
using AstFramework.Markup;
using VulcanEngine.AstFramework;
using Vulcan.Utility.Collections;
using System.Reflection;
using System.Collections.Generic;
using Vulcan.Utility.Xml;
using Vulcan.Utility.Common;
using Vulcan.Utility.Markup;

namespace VulcanEngine.IR.Ast.Task
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1501:AvoidExcessiveInheritance")]
    [FriendlyNameAttribute("PackageTemplate")]
    [AstSchemaTypeBindingAttribute("", "http://tempuri.org/vulcan2.xsd")]
    public partial class AstPackageTemplateNode : VulcanEngine.IR.Ast.AstTemplateNode
    {
        #region Private Storage
        private VulcanEngine.IR.Ast.Task.AstPackageBaseNode _package;

        #endregion Private Storage

        #region Public Accessor Properties
        [Browsable(false)]
        [AstXNameBinding("Package", ChildType.ChildDefinition, SubtypeOverride = typeof(VulcanEngine.IR.Ast.Task.AstPackageNode))]
        [AstXNameBinding("PackageTemplateInstance", ChildType.ChildDefinition, SubtypeOverride = typeof(VulcanEngine.IR.Ast.Task.AstPackageTemplateInstanceNode))]
        public VulcanEngine.IR.Ast.Task.AstPackageBaseNode Package
        {
            get { return _package; }
            set
            {
                if (_package != value)
                {
                    if (_package != null)
                    {
                        _package.Undefine();
                    }
                    VulcanEngine.IR.Ast.Task.AstPackageBaseNode oldValue = _package;
                    _package = value;
                    if (_package != null)
                    {
                        _package.DefineSymbol();
                    }
                    VulcanOnPropertyChanged("Package", oldValue, _package);
                }
            }
        }


        #endregion Public Accessor Properties

        #region Collection Methods

        #endregion Collection Methods

        #region Initialization
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        private void InitializeAstNode()
        {
        }

        #endregion Initialization

        public override VulcanCollection<IFrameworkItem> DefinedAstNodes()
        {
            var definedAstNodes = new VulcanCollection<IFrameworkItem>();
            definedAstNodes.AddRange(base.DefinedAstNodes());
            if (_package != null)
            {
                definedAstNodes.Add(_package);
            }

            return definedAstNodes;
        }


        public override IEnumerable<IScopeBoundary> BindingScopeBoundaries()
        {
            var bindingScopeBoundaries = new List<IScopeBoundary>();
            bindingScopeBoundaries.Add(ScopeBoundary);
            return bindingScopeBoundaries;
        }


        #region Cloning Support
        public override IFrameworkItem Clone()
        {
            return Clone(ParentItem);
        }

        public override IFrameworkItem Clone(Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            return Clone(ParentItem, cloneMapping);
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem)
        {
            return Clone(parentItem, new Dictionary<IFrameworkItem, IFrameworkItem>());
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            SymbolTable.GetSourceToCloneDefinitionMappings(this, parentItem, cloneMapping);
            CloneInto(cloneMapping[this], cloneMapping);
            return cloneMapping[this];
        }

        public override void CloneInto(IFrameworkItem targetItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            base.CloneInto(targetItem, cloneMapping);
            if (targetItem == null || !typeof(AstPackageTemplateNode).IsAssignableFrom(targetItem.GetType()))
            {
                throw new ArgumentException("Provided target node is not of the correct type.");
            }
            var castedTargetItem = (AstPackageTemplateNode)targetItem;
            if (_package == null)
            {
                castedTargetItem._package = null;
            }
            else if (cloneMapping.ContainsKey(_package))
            {
                castedTargetItem._package = (VulcanEngine.IR.Ast.Task.AstPackageBaseNode)cloneMapping[_package];
                _package.CloneInto(cloneMapping[_package], cloneMapping);
            }
            else
            {
                castedTargetItem._package = _package;
            }

        }

        public override IFrameworkItem CloneHusk(IFrameworkItem parentItem)
        {
            return new AstPackageTemplateNode(parentItem);
        }

        #endregion Cloning Support


    }
}
