//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Varigence Ast Designer tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.  Do not edit this file unless you know exactly
//     you are doing and are synchronized with the Vulcan development team.
//
//     For more information about the Varigence Ast Designer tool, email
//     support@varigence.com.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Specialized;
using Vulcan.Utility.ComponentModel;
using AstFramework;
using AstFramework.Engine.Binding;
using AstFramework.Model;
using AstFramework.Markup;
using VulcanEngine.AstFramework;
using Vulcan.Utility.Collections;
using System.Reflection;
using System.Collections.Generic;
using Vulcan.Utility.Xml;
using Vulcan.Utility.Common;
using Vulcan.Utility.Markup;

namespace VulcanEngine.IR.Ast.Task
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1501:AvoidExcessiveInheritance")]
    [FriendlyNameAttribute("RetryContainer")]
    [AstSchemaTypeBindingAttribute("", "http://tempuri.org/vulcan2.xsd")]
    public partial class AstRetryContainerTaskNode : VulcanEngine.IR.Ast.Task.AstContainerTaskNode
    {
        #region Private Storage
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields")]
        protected System.Int32 RetryCount_BackingField;
        private bool _isRetryCountExplicitlySet;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields")]
        protected System.Boolean BreakOnError_BackingField;
        private bool _isBreakOnErrorExplicitlySet;

        #endregion Private Storage

        #region Public Accessor Properties
        [VulcanCategory("Required")]
        [Browsable(false)]
        [AstXNameBinding("RetryCount", ChildType.Attribute)]
        public System.Int32 RetryCount
        {
            get { return RetryCount_BackingField; }
            set
            {
                if (RetryCount_BackingField != value)
                {
                    System.Int32 oldValue = RetryCount_BackingField;
                    RetryCount_BackingField = value;
                    VulcanOnPropertyChanged("RetryCount", oldValue, RetryCount_BackingField);
                    IsRetryCountExplicitlySet = true;
                }
            }
        }

        public bool IsRetryCountExplicitlySet
        {
            get { return _isRetryCountExplicitlySet; }
            protected set
            {
                if (_isRetryCountExplicitlySet != value)
                {
                    bool oldValue = _isRetryCountExplicitlySet;
                    _isRetryCountExplicitlySet = value;
                    VulcanOnPropertyChanged("IsRetryCountExplicitlySet", oldValue, _isRetryCountExplicitlySet);
                }
            }
        }


        [VulcanCategory("Optional")]
        [VulcanDefaultValue(false)]
        [Browsable(false)]
        [AstXNameBinding("BreakOnError", ChildType.Attribute, DefaultValue = "false")]
        public System.Boolean BreakOnError
        {
            get { return BreakOnError_BackingField; }
            set
            {
                if (BreakOnError_BackingField != value)
                {
                    System.Boolean oldValue = BreakOnError_BackingField;
                    BreakOnError_BackingField = value;
                    VulcanOnPropertyChanged("BreakOnError", oldValue, BreakOnError_BackingField);
                    IsBreakOnErrorExplicitlySet = true;
                }
            }
        }

        public bool IsBreakOnErrorExplicitlySet
        {
            get { return _isBreakOnErrorExplicitlySet; }
            protected set
            {
                if (_isBreakOnErrorExplicitlySet != value)
                {
                    bool oldValue = _isBreakOnErrorExplicitlySet;
                    _isBreakOnErrorExplicitlySet = value;
                    VulcanOnPropertyChanged("IsBreakOnErrorExplicitlySet", oldValue, _isBreakOnErrorExplicitlySet);
                }
            }
        }


        #endregion Public Accessor Properties

        #region Collection Methods


        #endregion Collection Methods

        #region Initialization
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        private void InitializeAstNode()
        {
            BreakOnError_BackingField = false;
        }

        #endregion Initialization

        public override VulcanCollection<IFrameworkItem> DefinedAstNodes()
        {
            var definedAstNodes = new VulcanCollection<IFrameworkItem>();
            definedAstNodes.AddRange(base.DefinedAstNodes());


            return definedAstNodes;
        }


        public override IEnumerable<IScopeBoundary> BindingScopeBoundaries()
        {
            var bindingScopeBoundaries = new List<IScopeBoundary>();
            bindingScopeBoundaries.Add(ScopeBoundary);
            return bindingScopeBoundaries;
        }


        #region Cloning Support
        public override IFrameworkItem Clone()
        {
            return Clone(ParentItem);
        }

        public override IFrameworkItem Clone(Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            return Clone(ParentItem, cloneMapping);
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem)
        {
            return Clone(parentItem, new Dictionary<IFrameworkItem, IFrameworkItem>());
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            SymbolTable.GetSourceToCloneDefinitionMappings(this, parentItem, cloneMapping);
            CloneInto(cloneMapping[this], cloneMapping);
            return cloneMapping[this];
        }

        public override void CloneInto(IFrameworkItem targetItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            base.CloneInto(targetItem, cloneMapping);
            if (targetItem == null || !typeof(AstRetryContainerTaskNode).IsAssignableFrom(targetItem.GetType()))
            {
                throw new ArgumentException("Provided target node is not of the correct type.");
            }
            var castedTargetItem = (AstRetryContainerTaskNode)targetItem;
            castedTargetItem.RetryCount_BackingField = RetryCount_BackingField;

            castedTargetItem.BreakOnError_BackingField = BreakOnError_BackingField;

        }

        public override IFrameworkItem CloneHusk(IFrameworkItem parentItem)
        {
            return new AstRetryContainerTaskNode(parentItem);
        }

        #endregion Cloning Support


    }
}
