//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Varigence Ast Designer tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.  Do not edit this file unless you know exactly
//     you are doing and are synchronized with the Vulcan development team.
//
//     For more information about the Varigence Ast Designer tool, email
//     support@varigence.com.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Specialized;
using Vulcan.Utility.ComponentModel;
using AstFramework;
using AstFramework.Engine.Binding;
using AstFramework.Model;
using AstFramework.Markup;
using VulcanEngine.AstFramework;
using Vulcan.Utility.Collections;
using System.Reflection;
using System.Collections.Generic;
using Vulcan.Utility.Xml;
using Vulcan.Utility.Common;
using Vulcan.Utility.Markup;

namespace VulcanEngine.IR.Ast.Task
{
    [AstSchemaTypeBindingAttribute("TaskflowInputsElemType", "http://tempuri.org/vulcan2.xsd")]
    public partial class AstTaskflowPrecedenceConstraintsNode : VulcanEngine.IR.Ast.AstNode
    {
        #region Private Storage
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields")]
        protected VulcanEngine.IR.Ast.Task.LogicalOperationType LogicalType_BackingField;
        private bool _isLogicalTypeExplicitlySet;

        private VulcanCollection<VulcanEngine.IR.Ast.Task.AstTaskflowInputPathNode> _inputs;

        #endregion Private Storage

        #region Public Accessor Properties
        [VulcanCategory("Optional")]
        [VulcanDefaultValue(VulcanEngine.IR.Ast.Task.LogicalOperationType.And)]
        [VulcanDescription(@"")]
        [Browsable(true)]
        [AstXNameBinding("LogicalType", ChildType.Attribute, DefaultValue = "And")]
        public VulcanEngine.IR.Ast.Task.LogicalOperationType LogicalType
        {
            get { return LogicalType_BackingField; }
            set
            {
                if (LogicalType_BackingField != value)
                {
                    VulcanEngine.IR.Ast.Task.LogicalOperationType oldValue = LogicalType_BackingField;
                    LogicalType_BackingField = value;
                    VulcanOnPropertyChanged("LogicalType", oldValue, LogicalType_BackingField);
                    IsLogicalTypeExplicitlySet = true;
                }
            }
        }

        public bool IsLogicalTypeExplicitlySet
        {
            get { return _isLogicalTypeExplicitlySet; }
            protected set
            {
                if (_isLogicalTypeExplicitlySet != value)
                {
                    bool oldValue = _isLogicalTypeExplicitlySet;
                    _isLogicalTypeExplicitlySet = value;
                    VulcanOnPropertyChanged("IsLogicalTypeExplicitlySet", oldValue, _isLogicalTypeExplicitlySet);
                }
            }
        }


        [VulcanCategory("Optional")]
        [VulcanDescription(@"")]
        [Browsable(true)]
        [AstXNameBinding("Input", ChildType.ListChildDefinition)]
        public VulcanCollection<VulcanEngine.IR.Ast.Task.AstTaskflowInputPathNode> Inputs
        {
            get { return _inputs; }
        }


        #endregion Public Accessor Properties

        #region Collection Methods

        private void _inputs_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            VulcanOnCollectionPropertyChanged("Inputs", e);
        }

        #endregion Collection Methods

        #region Initialization
        private void InitializeAstNode()
        {
            LogicalType_BackingField = VulcanEngine.IR.Ast.Task.LogicalOperationType.And;
            _inputs = new VulcanCollection<VulcanEngine.IR.Ast.Task.AstTaskflowInputPathNode>();
            _inputs.CollectionChanged += _inputs_CollectionChanged;
        }

        #endregion Initialization

        public override VulcanCollection<IFrameworkItem> DefinedAstNodes()
        {
            var definedAstNodes = new VulcanCollection<IFrameworkItem>();
            definedAstNodes.AddRange(base.DefinedAstNodes());

            foreach (var item in _inputs)
            {
                definedAstNodes.Add(item);
            }

            return definedAstNodes;
        }


        public override IEnumerable<IScopeBoundary> BindingScopeBoundaries()
        {
            var bindingScopeBoundaries = new List<IScopeBoundary>();
            bindingScopeBoundaries.Add(ScopeBoundary);
            return bindingScopeBoundaries;
        }


        #region Cloning Support
        public override IFrameworkItem Clone()
        {
            return Clone(ParentItem);
        }

        public override IFrameworkItem Clone(Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            return Clone(ParentItem, cloneMapping);
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem)
        {
            return Clone(parentItem, new Dictionary<IFrameworkItem, IFrameworkItem>());
        }

        public override IFrameworkItem Clone(IFrameworkItem parentItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            SymbolTable.GetSourceToCloneDefinitionMappings(this, parentItem, cloneMapping);
            CloneInto(cloneMapping[this], cloneMapping);
            return cloneMapping[this];
        }

        public override void CloneInto(IFrameworkItem targetItem, Dictionary<IFrameworkItem, IFrameworkItem> cloneMapping)
        {
            base.CloneInto(targetItem, cloneMapping);
            if (targetItem == null || !typeof(AstTaskflowPrecedenceConstraintsNode).IsAssignableFrom(targetItem.GetType()))
            {
                throw new ArgumentException("Provided target node is not of the correct type.");
            }
            var castedTargetItem = (AstTaskflowPrecedenceConstraintsNode)targetItem;
            castedTargetItem.LogicalType_BackingField = LogicalType_BackingField;

            foreach (var item in _inputs)
            {
                IFrameworkItem candidate = cloneMapping[item];
                castedTargetItem._inputs.Add((VulcanEngine.IR.Ast.Task.AstTaskflowInputPathNode)candidate);
                item.CloneInto(candidate, cloneMapping);
            }

        }

        public override IFrameworkItem CloneHusk(IFrameworkItem parentItem)
        {
            return new AstTaskflowPrecedenceConstraintsNode(parentItem);
        }

        #endregion Cloning Support


    }
}
