//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VulcanEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VulcanEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to create a duplicate IR Flow Vector: {0} -&gt; {1}.
        /// </summary>
        internal static string ErrorAttemptedWorkflowDuplicateIRFlowVector {
            get {
                return ResourceManager.GetString("ErrorAttemptedWorkflowDuplicateIRFlowVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to create multiple Vulcan Phase Workflows with the same name.
        /// </summary>
        internal static string ErrorAttemptedWorkflowDuplicatename {
            get {
                return ResourceManager.GetString("ErrorAttemptedWorkflowDuplicatename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to add a phase with a duplicate workflow unique phase name: {0}.
        /// </summary>
        internal static string ErrorAttemptedWorkflowDuplicateUniquePhaseName {
            get {
                return ResourceManager.GetString("ErrorAttemptedWorkflowDuplicateUniquePhaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to create workflow self-loop on phase: {0}.
        /// </summary>
        internal static string ErrorAttemptedWorkflowSelfLoop {
            get {
                return ResourceManager.GetString("ErrorAttemptedWorkflowSelfLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to supply duplicate IR along a Phase IR Flow Vector: {0} -&gt; {1}.
        /// </summary>
        internal static string ErrorAttemptedWorkflowSupplyDuplicatePhaseIR {
            get {
                return ResourceManager.GetString("ErrorAttemptedWorkflowSupplyDuplicatePhaseIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate phase friendly name was found: {0}.
        /// </summary>
        internal static string ErrorDuplicatePhaseFriendlyNameFound {
            get {
                return ResourceManager.GetString("ErrorDuplicatePhaseFriendlyNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Duplicate Phase Parameter Was Specified: {0} , {1}.
        /// </summary>
        internal static string ErrorDuplicatePhaseParameterSpecified {
            get {
                return ResourceManager.GetString("ErrorDuplicatePhaseParameterSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phase Parameter Type Specified: {0} , {1}.
        /// </summary>
        internal static string ErrorInvalidPhaseParameterType {
            get {
                return ResourceManager.GetString("ErrorInvalidPhaseParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified default Vulcan Phase Workflow does not exist.
        /// </summary>
        internal static string ErrorInvalidWorkflowDefaultName {
            get {
                return ResourceManager.GetString("ErrorInvalidWorkflowDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase name not registered: {0}.
        /// </summary>
        internal static string ErrorInvalidWorkflowPhaseSpecifier {
            get {
                return ResourceManager.GetString("ErrorInvalidWorkflowPhaseSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR Merging Not Yet Supported: {0}.
        /// </summary>
        internal static string ErrorIRMergingNotYetSupported {
            get {
                return ResourceManager.GetString("ErrorIRMergingNotYetSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate MessageEngine name already exists: {0}.
        /// </summary>
        internal static string ErrorMessageEngineNameDuplicate {
            get {
                return ResourceManager.GetString("ErrorMessageEngineNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR List supplied to workflow phase was empty: {0}.
        /// </summary>
        internal static string ErrorPhaseInputIRListEmpty {
            get {
                return ResourceManager.GetString("ErrorPhaseInputIRListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified constuctor not found in phase: {0}.  Remember that all Phase constructors must accept a string parameter for WorkflowUniqueName..
        /// </summary>
        internal static string ErrorPhaseLacksSpecifiedConstructor {
            get {
                return ResourceManager.GetString("ErrorPhaseLacksSpecifiedConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wrong IR Type ({0}) was supplied to Phase: {1}.
        /// </summary>
        internal static string ErrorPhaseWorkflowIncorrectInputIRType {
            get {
                return ResourceManager.GetString("ErrorPhaseWorkflowIncorrectInputIRType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Type Converter Does Not Exist: {0}.
        /// </summary>
        internal static string ErrorRequiredTypeConverterDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorRequiredTypeConverterDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified phase name was not found: {0}.
        /// </summary>
        internal static string ErrorSpecifiedPhaseNameNotFound {
            get {
                return ResourceManager.GetString("ErrorSpecifiedPhaseNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type {0} is not supported..
        /// </summary>
        internal static string ErrorUnknownDocType {
            get {
                return ResourceManager.GetString("ErrorUnknownDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cycle was detected in the Phase Workflow graph: {0}.
        /// </summary>
        internal static string ErrorWorkflowCycleDetected {
            get {
                return ResourceManager.GetString("ErrorWorkflowCycleDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml Validation Error: {0}.
        /// </summary>
        internal static string ErrorXmlValidation {
            get {
                return ResourceManager.GetString("ErrorXmlValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string NamespaceSeparator {
            get {
                return ResourceManager.GetString("NamespaceSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulcan File Not Found: {0}.
        /// </summary>
        internal static string VulcanFileNotFound {
            get {
                return ResourceManager.GetString("VulcanFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Vulcan Version .
        /// </summary>
        internal static string VulcanStart {
            get {
                return ResourceManager.GetString("VulcanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source {0} or Destination {1} does not exist in {2} : {3}.
        /// </summary>
        internal static string WarningMapColumnsDoNotExist {
            get {
                return ResourceManager.GetString("WarningMapColumnsDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phase with type {0} has multiple friendly names defined..
        /// </summary>
        internal static string WarningMultiplePhaseFriendlyNames {
            get {
                return ResourceManager.GetString("WarningMultiplePhaseFriendlyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PreProcessor found.
        /// </summary>
        internal static string WarningNoPreProcessorFound {
            get {
                return ResourceManager.GetString("WarningNoPreProcessorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlValidation Warning: {0}.
        /// </summary>
        internal static string WarningXmlValidation {
            get {
                return ResourceManager.GetString("WarningXmlValidation", resourceCulture);
            }
        }
    }
}
